---
title: "Tables"
author: "Collin Owens"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(reactablefmtr)
```

# Data reading and conversions
```{r}
NBAData <- read.csv("D:\\GradSchool\\STA 566\\Data\\player_data.csv")
NBAData$year_start <- as.factor(NBAData$year_start)

NBAData <- NBAData[!(NBAData$name == "George Karl"),]

NBAData <- NBAData %>% separate(height, c('feet', 'inches'), "-", convert = TRUE) %>% mutate(cm = (12*feet + inches)*2.54)
NBAData <- NBAData %>% separate(position, c('Primary', 'Secondary'), "-", convert = TRUE)


```
# Data set up
```{r}
#Overall NBA height
HData <- NBAData %>% group_by(year_start) %>% summarise(mean(cm))
names(HData)[1] <- "YrStart"
names(HData)[2] <- "HeightCM"

#Guard height
GuardPositionData <- NBAData %>% filter(Primary == "G") %>% group_by(year_start) %>% summarise(mean(cm))
names(GuardPositionData)[1] <- "YrStart"
names(GuardPositionData)[2] <- "HeightCM"

#Forward height
ForwardPositionData <- NBAData %>% filter(Primary == "F") %>% group_by(year_start) %>% summarise(mean(cm))
names(ForwardPositionData)[1] <- "YrStart"
names(ForwardPositionData)[2] <- "HeightCM"

#Center height
CenterPositionData <- NBAData %>% filter(Primary == "F") %>% group_by(year_start) %>% summarise(mean(cm))
names(CenterPositionData)[1] <- "YrStart"
names(CenterPositionData)[2] <- "HeightCM"

#Htable <- HData %>% select(YrStart, HeightCM) %>% mutate(Heightplt = NA) %>% as.data.frame()


```

# NBA all player height table average by year

```{r}
PercentChange <- (HData$HeightCM-lag(HData$HeightCM))/HData$HeightCM*100

HData$HPercentChange <- PercentChange

NBAReactbl <- HData %>% reactable(columns = list(YrStart = colDef(name = "Starting year"), HeightCM = colDef(name = "Average NBA height in CM", format = colFormat(digits = 1)), HPercentChange = colDef(name = "Height percent change", format = colFormat(digits = 1),cell = data_bars(., 
                                           fill_color = c("pink","lightgreen"),
                                           number_fmt=scales::number_format(accuracy=.1)))))

NBAReactbl
```

# NBA Guard average height data by year
```{r}
PercentChange <- (GuardPositionData$HeightCM-lag(GuardPositionData$HeightCM))/GuardPositionData$HeightCM*100

GuardPositionData$HPercentChange <- PercentChange

GuardReactbl <- GuardPositionData %>% reactable(columns = list(YrStart = colDef(name = "Starting year"), HeightCM = colDef(name = "Average Guard height in CM", format = colFormat(digits = 1)), HPercentChange = colDef(name = "Height percent change", format = colFormat(digits = 1),cell = data_bars(., 
                                           fill_color = c("pink","lightgreen"),
                                           number_fmt=scales::number_format(accuracy=.1)))))

GuardReactbl
```


# NBA Forward average height data by year
```{r}
PercentChange <- (ForwardPositionData$HeightCM-lag(ForwardPositionData$HeightCM))/ForwardPositionData$HeightCM*100

ForwardPositionData$HPercentChange <- PercentChange

ForwardReactbl <- ForwardPositionData %>% reactable(columns = list(YrStart = colDef(name = "Starting year"), HeightCM = colDef(name = "Average Forward height in CM", format = colFormat(digits = 1)), HPercentChange = colDef(name = "Height percent change", format = colFormat(digits = 1),cell = data_bars(., 
                                           fill_color = c("pink","lightgreen"),
                                           number_fmt=scales::number_format(accuracy=.1)))))

ForwardReactbl
```

# NBA Forward average height data by year
```{r}
PercentChange <- (CenterPositionData$HeightCM-lag(CenterPositionData$HeightCM))/CenterPositionData$HeightCM*100

CenterPositionData$HPercentChange <- PercentChange

CenterReactbl <- CenterPositionData %>% reactable(columns = list(YrStart = colDef(name = "Starting year"), HeightCM = colDef(name = "Average Center height in CM", format = colFormat(digits = 1)), HPercentChange = colDef(name = "Height percent change", format = colFormat(digits = 1),cell = data_bars(., 
                                           fill_color = c("pink","lightgreen"),
                                           number_fmt=scales::number_format(accuracy=.1)))))

CenterReactbl
```

